# Generated by Django 5.2.12 on 2026-09-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category", "featured"],
                name="shop_prod_catalog_idx",
            ),
        ),
    ]
