# Generated by Django 5.2.12 on 2026-09-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_shop_prod_catalog_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("home", "Página inicial"), ("about", "Sobre")],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("eyebrow", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=150)),
                ("copy", models.CharField(blank=True, max_length=260)),
                ("image_url", models.CharField(max_length=320)),
                ("image_alt", models.CharField(max_length=180)),
                ("button_label", models.CharField(blank=True, max_length=60)),
                ("button_url", models.CharField(blank=True, max_length=320)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "pk"],
                "indexes": [
                    models.Index(
                        fields=["page", "is_active", "order"],
                        name="shop_slide_live_order_idx",
                    )
                ],
            },
        ),
    ]
