# Generated by Django 5.2.12 on 2026-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_carouselslide_accent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselslide",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Página inicial"),
                    ("about", "Sobre"),
                    ("about_2", "Sobre — segundo carrossel"),
                ],
                db_index=True,
                max_length=12,
            ),
        ),
    ]
