from typing import Iterable, Protocol

from shop.domain.entities.catalog import CatalogPage, Product


class CatalogRepository(Protocol):
    def list_active(self, category: str = "", query: str = "", exclude_slug: str = "", limit: int | None = None) -> list[Product]: ...

    def list_active_page(self, *, category: str = "", query: str = "", page_number: int = 1, per_page: int = 6) -> CatalogPage: ...

    def list_categories(self) -> list[tuple[str, str]]: ...

    def get_by_slug(self, slug: str) -> Product | None: ...

    def get_by_id(self, product_id: int) -> Product | None: ...

    def get_by_ids(self, product_ids: Iterable[int | str]) -> list[Product]: ...

    def get_detail_by_slug(self, slug: str) -> tuple[Product | None, list[Product]]: ...
